[package]
name = "local_train_tracks"
version = "0.1.0"
edition = "2021"
default-run = "runner"

[[bin]]
name = "bot"
path = "src/bin_bot.rs"

[[bin]]
name = "runner"
path = "src/bin_runner.rs"

[[bin]]
name = "test"
path = "src/bin_test.rs"

[[bin]]
name = "testgui"
path = "src/bin_testegui.rs"

[profile.release]
opt-level = 3

[dependencies]
eframe = "0.36.2"
egui = "0.36.2"

